# Frame extraction settings
fps: 0.5  # Frames per second (1 means 1 frame is saved every second)
resolution: "336x336"  # Resolution of extracted frames (width x height)

# File paths
base_path: "/home/ratul/Workstation/ratul/VLM_case_study"  
video_dir: "${base_path}/database/videos"
frame_dir: "${base_path}/database/frames"

# YouTube video links
video_links:
  - "https://www.youtube.com/watch?v=hWp9vZ7eeaM&ab_channel=Gurka"
  - "https://www.youtube.com/watch?v=TnYQ_dO4v30&ab_channel=Gurka"
